<?php
function rwb_appcache_get_hash() {
    $str = '';
    foreach (array(
        __DIR__,
        __DIR__ . '/conf'
    ) as $dir) {
        foreach (scandir($dir) as $file) {
            $str .= md5_file($dir . '/' . $file);
        }
    }
    return md5($str);
}

$hash=rwb_appcache_get_hash();

$info = <<<INFO
<?php
# This file is auto generated by build.php and ignored in Git.

define('RWB_APPCACHE_HASH','$hash');

INFO;

file_put_contents('./info.php',$info);

echo 'Build OK!';
echo "\n";
